export const queryKeys = {
  me: ['users', 'me'] as const,
  donorProfile: ['donors', 'profile'] as const,
  notifications: ['notifications'] as const,
  notificationsUnread: ['notifications', 'unread'] as const,
  bloodRequests: ['blood-requests'] as const,
  myBloodRequests: ['blood-requests', 'my'] as const,
  bloodRequest: (id: string) => ['blood-requests', id] as const,
  matches: (id: string) => ['blood-requests', id, 'matches'] as const,
  emergencyRequests: ['emergency-requests'] as const,
  emergencyRequest: (id: string) => ['emergency-requests', id] as const,
  donations: ['donations'] as const,
  appointments: ['appointments'] as const,
  appointment: (id: string) => ['appointments', id] as const,
  inventory: (hospitalId: string) => ['inventory', hospitalId] as const,
  hospitals: ['hospitals'] as const,
  hospital: (id: string) => ['hospitals', id] as const,
  contributions: (donorId: string) => ['donors', donorId, 'contributions'] as const,
  analytics: ['analytics'] as const,
  auditLogs: ['audit-logs'] as const,
  adminUsers: ['admin', 'users'] as const,
  adminDonors: ['admin', 'donors'] as const,
  adminHospitals: ['admin', 'hospitals'] as const,
};
