package com.redpulse.enums;

public enum NotificationType {
    BLOOD_REQUEST,
    DONATION_REQUEST,
    DONATION_ACCEPTED,
    APPOINTMENT,
    APPOINTMENT_CREATED,
    APPOINTMENT_CONFIRMED,
    APPOINTMENT_REMINDER,
    APPOINTMENT_CANCELLED,
    APPOINTMENT_COMPLETED,
    DONATION_COMPLETED,
    BADGE_EARNED,
    CONTRIBUTION_UPDATED,
    EMERGENCY,
    SYSTEM
}
